# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Mod Properties
version=1.3.1
maven_group=net.inventive-mods
archives_base_name=inventive-inventory

# Fabric Properties
minecraft_version=1.21.9
yarn_mappings=1.21.9+build.1
loader_version=0.16.14

# Dependencies
fabric_version=0.133.14+1.21.9
modmenu_version=15.0.0-beta.3